import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.scss";
import {NebulaBackground} from "@/app/NebulaBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nebulous",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <NebulaBackground />
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
